version: '2'

networks:
  chat-net:

services:
  chat-server:
    container_name: chat-server
    image: golang
    working_dir: /go/src/github.com/bandreghetti/go-chat/server
    command: go run .
    volumes:
    - ./server:/go/src/github.com/bandreghetti/go-chat/server
    - ./msgs:/go/src/github.com/bandreghetti/go-chat/msgs
    networks:
      - chat-net
    ports:
      - 6174:6174

  chat-alice:
    stdin_open: true
    tty: true
    container_name: chat-alice
    image: golang
    working_dir: /go/src/github.com/bandreghetti/go-chat/client
    command: go run main.go
    volumes:
    - ./client:/go/src/github.com/bandreghetti/go-chat/client
    - ./msgs:/go/src/github.com/bandreghetti/go-chat/msgs
    networks:
      - chat-net

  chat-bruno:
    stdin_open: true
    tty: true
    container_name: chat-bruno
    image: golang
    working_dir: /go/src/github.com/bandreghetti/go-chat/client
    command: go run main.go
    volumes:
    - ./client:/go/src/github.com/bandreghetti/go-chat/client
    - ./msgs:/go/src/github.com/bandreghetti/go-chat/msgs
    networks:
      - chat-net

  chat-caio:
    stdin_open: true
    tty: true
    container_name: chat-caio
    image: golang
    working_dir: /go/src/github.com/bandreghetti/go-chat/client
    command: go run main.go
    volumes:
    - ./client:/go/src/github.com/bandreghetti/go-chat/client
    - ./msgs:/go/src/github.com/bandreghetti/go-chat/msgs
    networks:
      - chat-net
